### ISSUE TITLE
Question: Can this library be used to parse dot file?

### ISSUE THREAD

**Issue by pavel-agarkov** [abock/dotlang#1]
I want to parse and analyze graph from dot file to then use data about node relations in my computations.
Can Lexer output be helpful or it is easier to convert dot file to json and analyze it then?

**Comment by abock** [comment]
This library provides a full lexer and parser for the dot language. Running your dot file through the parser will provide you a full AST of the nodes/edges. So to answer your question, yes, I think you can use this library to do what you need.
